GET http://localhost:3000/v1/users/65199fe5a784b008701baa34
############# CREAR PELICULA
POST http://localhost:3000/v1/users
Content-Type:  application/json

  {
    "name": "Test hash",
    "second_name": "test",
    "email" : "test@gmail.com",
    "password": "password"
   
  }
#########
GET http://localhost:3000/v1/users
#########

DELETE  http://localhost:3000/v1/users
Content-Type:  application/json

  {
   "_id":"65199fe5a784b008701baa34"
   
  }

###
PUT http://localhost:3000/v1/users/651d84fcbb9f1e04e2af5172

content-type: application/json

  {
    "name": "Joel UPDATE",
    "second_name": "test",
    "email": "test@gmail.com",
  }